/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AuthorizationInterface extends ethers.utils.Interface {
  functions: {
    "ROLE_ADMIN()": FunctionFragment;
    "ROLE_ASSIGNMENT_DELAY_SECS()": FunctionFragment;
    "ROLE_DASHBOARD_VIEWER()": FunctionFragment;
    "_accountRoleAssigned(address)": FunctionFragment;
    "_accoutRoleAssignmentTime(address)": FunctionFragment;
    "assignRole(address,bytes4)": FunctionFragment;
    "getUserRole(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeRole(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ROLE_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_ASSIGNMENT_DELAY_SECS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_DASHBOARD_VIEWER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_accountRoleAssigned",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_accoutRoleAssignmentTime",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRole",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getUserRole", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "revokeRole", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "ROLE_ADMIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_ASSIGNMENT_DELAY_SECS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_DASHBOARD_VIEWER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_accountRoleAssigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_accoutRoleAssignmentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "RoleAssigned(address,bytes4)": EventFragment;
    "RoleRevoked(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAssigned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type RoleAssignedEvent = TypedEvent<
  [string, string] & { to: string; role: string }
>;

export type RoleRevokedEvent = TypedEvent<[string] & { who: string }>;

export class Authorization extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AuthorizationInterface;

  functions: {
    ROLE_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    ROLE_ASSIGNMENT_DELAY_SECS(overrides?: CallOverrides): Promise<[BigNumber]>;

    ROLE_DASHBOARD_VIEWER(overrides?: CallOverrides): Promise<[string]>;

    _accountRoleAssigned(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _accoutRoleAssignmentTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    assignRole(
      _to: string,
      _role: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getUserRole(_who: string, overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ROLE_ADMIN(overrides?: CallOverrides): Promise<string>;

  ROLE_ASSIGNMENT_DELAY_SECS(overrides?: CallOverrides): Promise<BigNumber>;

  ROLE_DASHBOARD_VIEWER(overrides?: CallOverrides): Promise<string>;

  _accountRoleAssigned(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  _accoutRoleAssignmentTime(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  assignRole(
    _to: string,
    _role: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getUserRole(_who: string, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ROLE_ADMIN(overrides?: CallOverrides): Promise<string>;

    ROLE_ASSIGNMENT_DELAY_SECS(overrides?: CallOverrides): Promise<BigNumber>;

    ROLE_DASHBOARD_VIEWER(overrides?: CallOverrides): Promise<string>;

    _accountRoleAssigned(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    _accoutRoleAssignmentTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assignRole(
      _to: string,
      _role: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getUserRole(_who: string, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revokeRole(_to: string, overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "RoleAssigned(address,bytes4)"(
      to?: string | null,
      role?: null
    ): TypedEventFilter<[string, string], { to: string; role: string }>;

    RoleAssigned(
      to?: string | null,
      role?: null
    ): TypedEventFilter<[string, string], { to: string; role: string }>;

    "RoleRevoked(address)"(
      who?: string | null
    ): TypedEventFilter<[string], { who: string }>;

    RoleRevoked(
      who?: string | null
    ): TypedEventFilter<[string], { who: string }>;
  };

  estimateGas: {
    ROLE_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    ROLE_ASSIGNMENT_DELAY_SECS(overrides?: CallOverrides): Promise<BigNumber>;

    ROLE_DASHBOARD_VIEWER(overrides?: CallOverrides): Promise<BigNumber>;

    _accountRoleAssigned(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _accoutRoleAssignmentTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assignRole(
      _to: string,
      _role: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getUserRole(_who: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ROLE_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ROLE_ASSIGNMENT_DELAY_SECS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ROLE_DASHBOARD_VIEWER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _accountRoleAssigned(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _accoutRoleAssignmentTime(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assignRole(
      _to: string,
      _role: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getUserRole(
      _who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
